In [1]:
import sys

!{sys.executable} -m pip install --upgrade pandas

!{sys.executable} -m pip install --upgrade --force-reinstall pandas
import pandas as pd

Requirement already satisfied: pandas in c:\users\acer\appdata\local\programs\python\python311\lib\site-packages (2.3.3)
Collecting pandas
  Using cached pandas-3.0.6-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\acer\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\acer\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\users\acer\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.6-cp311-cp311-win_amd64.whl (9.9 MB)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.3.3
    Uninstalling pandas-2.3.3:
      Successfully uninstalled pandas-2.3.3
Successfully installed pandas-3.0.6

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

^C

In [ ]:
train_identity=pd.read_csv("../data/raw/train_identity.csv")
train_transaction=pd.read_csv("../data/raw/train_transaction.csv")

In [ ]:
train_identity.shape

(144233, 41)

In [4]:
train_identity.head()

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

In [5]:
train_transaction.shape

(590540, 394)

In [6]:
train_transaction.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
merged_df = pd.merge(train_transaction, train_identity, on="TransactionID", how="left")

In [8]:
print(merged_df.shape)

(590540, 434)

In [9]:
memory_used=merged_df.memory_usage(deep=True).sum()
print("Memory usage: ", memory_used, "bytes")
print("Memory usage: ", memory_used/(1024**2), "MB")

Memory usage:  2080582559 bytes
Memory usage:  1984.1981496810913 MB

In [10]:
merged_df.info

<bound method DataFrame.info of         TransactionID  isFraud  TransactionDT  TransactionAmt ProductCD  \
0             2987000        0          86400           68.50         W
1             2987001        0          86401           29.00         W
2             2987002        0          86469           59.00         W
3             2987003        0          86499           50.00         W
4             2987004        0          86506           50.00         H
...               ...      ...            ...             ...       ...
590535        3577535        0       15811047           49.00         W
590536        3577536        0       15811049           39.50         W
590537        3577537        0       15811079           30.95         W
590538        3577538        0       15811088          117.00         W
590539        3577539        0       15811131          279.95         W

        card1  card2  card3       card4  card5  ...                id_31  \
0       13926    NaN  150.0    discover  142.0  ...                  NaN
1        2755  404.0  150.0  mastercard  102.0  ...                  NaN
2        4663  490.0  150.0        visa  166.0  ...                  NaN
3       18132  567.0  150.0  mastercard  117.0  ...                  NaN
4        4497  514.0  150.0  mastercard  102.0  ...  samsung browser 6.2
...       ...    ...    ...         ...    ...  ...                  ...
590535   6550    NaN  150.0        visa  226.0  ...                  NaN
590536  10444  225.0  150.0  mastercard  224.0  ...                  NaN
590537  12037  595.0  150.0  mastercard  224.0  ...                  NaN
590538   7826  481.0  150.0  mastercard  224.0  ...                  NaN
590539  15066  170.0  150.0  mastercard  102.0  ...                  NaN

        id_32      id_33           id_34  id_35 id_36 id_37  id_38  \
0         NaN        NaN             NaN    NaN   NaN   NaN    NaN
1         NaN        NaN             NaN    NaN   NaN   NaN    NaN
2         NaN        NaN             NaN    NaN   NaN   NaN    NaN
3         NaN        NaN             NaN    NaN   NaN   NaN    NaN
4        32.0  2220x1080  match_status:2      T     F     T      T
...       ...        ...             ...    ...   ...   ...    ...
590535    NaN        NaN             NaN    NaN   NaN   NaN    NaN
590536    NaN        NaN             NaN    NaN   NaN   NaN    NaN
590537    NaN        NaN             NaN    NaN   NaN   NaN    NaN
590538    NaN        NaN             NaN    NaN   NaN   NaN    NaN
590539    NaN        NaN             NaN    NaN   NaN   NaN    NaN

        DeviceType                     DeviceInfo
0              NaN                            NaN
1              NaN                            NaN
2              NaN                            NaN
3              NaN                            NaN
4           mobile  SAMSUNG SM-G892A Build/NRD90M
...            ...                            ...
590535         NaN                            NaN
590536         NaN                            NaN
590537         NaN                            NaN
590538         NaN                            NaN
590539         NaN                            NaN

[590540 rows x 434 columns]>

In [11]:
merged_df.describe()

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\~~mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\~.mpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\~andas'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.4.6 which is incompatible.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Using cached pandas-3.0.6-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting python-dateutil>=2.8.2 (from pandas)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached pandas-3.0.6-cp311-cp311-win_amd64.whl (9.9 MB)
Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: tzdata, six, numpy, python-dateutil, pandas
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2026.4
    Uninstalling tzdata-2026.4:
      Successfully uninstalled tzdata-2026.4
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.6
    Uninstalling numpy-2.4.6:
      Successfully uninstalled numpy-2.4.6
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: pandas
    Found existing installation: pandas 3.0.6
    Uninstalling pandas-3.0.6:
      Successfully uninstalled pandas-3.0.6
Successfully installed numpy-2.4.6 pandas-3.0.6 python-dateutil-2.9.0.post0 six-1.17.0 tzdata-2026.4

,TransactionID,isFraud,TransactionDT,TransactionAmt,card1,card2,card3,card5,addr1,addr2,...,id_17,id_18,id_19,id_20,id_21,id_22,id_24,id_25,id_26,id_32
count,5.905400e+05,590540.000000,5.905400e+05,590540.000000,590540.000000,581607.000000,588975.000000,586281.000000,524834.000000,524834.000000,...,139369.000000,45113.000000,139318.000000,139261.000000,5159.000000,5169.000000,4747.000000,5132.000000,5163.000000,77586.000000
mean,3.282270e+06,0.034990,7.372311e+06,135.027176,9898.734658,362.555488,153.194925,199.278897,290.733794,86.800630,...,189.451377,14.237337,353.128174,403.882666,368.269820,16.002708,12.800927,329.608924,149.070308,26.508597
std,1.704744e+05,0.183755,4.617224e+06,239.162522,4901.170153,157.793246,11.336444,41.244453,101.741072,2.690623,...,30.375360,1.561302,141.095343,152.160327,198.847038,6.897665,2.372447,97.461089,32.101995,3.737502
min,2.987000e+06,0.000000,8.640000e+04,0.251000,1000.000000,100.000000,100.000000,100.000000,100.000000,10.000000,...,100.000000,10.000000,100.000000,100.000000,100.000000,10.000000,11.000000,100.000000,100.000000,0.000000
25%,3.134635e+06,0.000000,3.027058e+06,43.321000,6019.000000,214.000000,150.000000,166.000000,204.000000,87.000000,...,166.000000,13.000000,266.000000,256.000000,252.000000,14.000000,11.000000,321.000000,119.000000,24.000000
50%,3.282270e+06,0.000000,7.306528e+06,68.769000,9678.000000,361.000000,150.000000,226.000000,299.000000,87.000000,...,166.000000,15.000000,341.000000,472.000000,252.000000,14.000000,11.000000,321.000000,149.000000,24.000000
75%,3.429904e+06,0.000000,1.124662e+07,125.000000,14184.000000,512.000000,150.000000,226.000000,330.000000,87.000000,...,225.000000,15.000000,427.000000,533.000000,486.500000,14.000000,15.000000,371.000000,169.000000,32.000000
max,3.577539e+06,1.000000,1.581113e+07,31937.391000,18396.000000,600.000000,231.000000,237.000000,540.000000,102.000000,...,229.000000,29.000000,671.000000,661.000000,854.000000,44.000000,26.000000,548.000000,216.000000,32.000000

In [12]:
merged_df.dtypes

TransactionID       int64
isFraud             int64
TransactionDT       int64
TransactionAmt    float64
ProductCD             str
                   ...
id_36                 str
id_37                 str
id_38                 str
DeviceType            str
DeviceInfo            str
Length: 434, dtype: object

In [13]:
float_cols=merged_df.select_dtypes(include=['float64']).columns
merged_df[float_cols]=merged_df[float_cols].astype('float32')

In [14]:
int_cols=merged_df.select_dtypes(include=['int64']).columns
for cols in int_cols:
    merged_df[cols]=pd.to_numeric(merged_df[cols],downcast='integer')

In [15]:
text_cols=merged_df.select_dtypes(include=['object']).columns
merged_df[text_cols]=merged_df[text_cols].astype('category')

C:\Users\ACER\AppData\Local\Temp\ipykernel_14084\2285139049.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols=merged_df.select_dtypes(include=['object']).columns

In [16]:
memory_after=merged_df.memory_usage(deep=True).sum()
print("Memory usage after optimization: ", memory_after, "bytes")
print("Memory usage after optimization: ", memory_after/(1024**2), "MB")

Memory usage after optimization:  969132304 bytes
Memory usage after optimization:  924.2365875244141 MB

In [ ]:
from pathlib import Path

# Build the path to Data/interim, creating the folder if it doesn't exist
interim_dir = Path("Data/interim")

output_path = interim_dir / "train_merged.parquet"

# Save the merged, downcasted DataFrame
merged_df.to_parquet(output_path, engine="pyarrow", index=False)

print(f"Saved to: {output_path}")
print(f"File size: {output_path.stat().st_size / (1024**2):.2f} MB")

Saved to: Data\interim\train_merged.parquet
File size: 80.17 MB

In [3]:
import pandas as pd
new=pd.read_parquet("../Data/interim/train_merged.parquet")

In [4]:
new.shape

(590540, 434)

In [1]:
# Add src/ to Python's search path so it can find the fraud_triage package
import sys
sys.path.append("../src")

from fraud_triage.data.load import load_and_merge_raw_data

merged_df = load_and_merge_raw_data()
merged_df.shape

Saved to: D:\Fraud-Triage\fraud-triage\Data\interim\train_merged.parquet
Shape: (590540, 434)
File size: 80.17 MB

(590540, 434)